#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_HOST)
#define CFG_TUSB_DEBUG 0

#define CFG_TUD_HID 1
#define CFG_TUH_HID 1

#define CFG_TUD_ENDPOINT0_SIZE 64

#endif /* _TUSB_CONFIG_H_ */
