name: Build GP2040-CE for Pico2

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Pull the GP2040-CE source + submodules (tinyusb, pico_pio_usb)
      - name: Checkout GP2040-CE
        uses: actions/checkout@v4
        with:
          repository: OpenStickCommunity/GP2040-CE
          submodules: true

      # 2) Toolchain
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      # 3) Configure (fetch a known-good Pico SDK, target Pico2, and
      #    allow MbedTLS private access to satisfy PS4 sources)
      - name: Configure (Pico2)
        run: |
          cmake -S . -B build \
            -DPICO_BOARD=pico2 \
            -DPICO_SDK_FETCH_FROM_GIT=1 \
            -DPICO_SDK_GIT_TAG=2.1.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-DMBEDTLS_ALLOW_PRIVATE_ACCESS=1" \
            -DCMAKE_CXX_FLAGS="-DMBEDTLS_ALLOW_PRIVATE_ACCESS=1"

      # 4) Build
      - name: Build
        run: cmake --build build -j"$(nproc)"

      # 5) Show what got produced (helps debugging)
      - name: List UF2s
        run: find build -name '*.uf2' -maxdepth 3 -print

      # 6) Upload every UF2 it generated
      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gp2040ce-pico2
          path: build/**/*.uf2
