name: Build GP2040-CE Pico2

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GP2040-CE source
        uses: actions/checkout@v4
        with:
          repository: OpenStickCommunity/GP2040-CE
          submodules: recursive

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Configure & Build (Pico2)
        run: |
          cd GP2040-CE
          mkdir -p build
          cd build
          cmake .. -DPICO_BOARD=pico2
          make -j$(nproc)

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gp2040ce_pico2
          path: GP2040-CE/build/src/gp2040ce_pico2.uf2
