name: Build GP2040-CE Pico2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi git

      - name: Clone GP2040-CE source
        run: |
          git clone --recursive https://github.com/OpenStickCommunity/GP2040-CE.git
          cd GP2040-CE
          mkdir -p build
          cd build
          cmake .. \
            -DPICO_BOARD=pico2 \
            -DPICO_SDK_FETCH_FROM_GIT=1 \
            -DPICO_SDK_GIT_TAG=develop \
            -DFEATURE_PS4=0 -DFEATURE_PS5=0 -DFEATURE_XINPUT=0 \
            -DCMAKE_C_FLAGS="-DMBEDTLS_ALLOW_PRIVATE_ACCESS=1" \
            -DCMAKE_CXX_FLAGS="-DMBEDTLS_ALLOW_PRIVATE_ACCESS=1"
          make -j$(nproc)

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gp2040ce-pico2
          path: GP2040-CE/build/src/*.uf2
