name: Build Switch Bridge Pico

on:
  workflow_dispatch: # manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Set up Pico SDK
        run: |
          git clone --depth=1 https://github.com/raspberrypi/pico-sdk.git
          git -C pico-sdk submodule update --init
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. -DPICO_BOARD=pico -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: switch_bridge_pico
          path: build/*.uf2
