name: Build GP2040-CE Pico2

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git

      - name: Clone GP2040-CE source
        run: |
          git clone --recursive https://github.com/OpenStickCommunity/GP2040-CE.git
          cd GP2040-CE
          mkdir -p build
          cd build
          cmake .. -DPICO_BOARD=pico2
          make -j$(nproc)

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: gp2040ce_pico2
          path: GP2040-CE/build/src/gp2040ce_pico2.uf2
